In [76]:
import numpy as np
import pandas as pd
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis as QDA
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix

In [77]:
Smarket = pd.read_csv("/Users/arpanganguli/Documents/Finance/ISLR/Datasets/Smarket.csv", index_col = 'SlNo')

In [78]:
Smarket.head()

Year   Lag1   Lag2   Lag3   Lag4   Lag5  Volume  Today Direction
SlNo                                                                  
1     2001  0.381 -0.192 -2.624 -1.055  5.010  1.1913  0.959        Up
2     2001  0.959  0.381 -0.192 -2.624 -1.055  1.2965  1.032        Up
3     2001  1.032  0.959  0.381 -0.192 -2.624  1.4112 -0.623      Down
4     2001 -0.623  1.032  0.959  0.381 -0.192  1.2760  0.614        Up
5     2001  0.614 -0.623  1.032  0.959  0.381  1.2057  0.213        Up

In [79]:
X = np.array(Smarket[['Lag1', 'Lag2']])
y = np.array(Smarket['Direction'])
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2016, random_state=101)

In [80]:
qdafit = QDA().fit(X_train, y_train)

In [81]:
qdafit.priors_

array([0.48496994, 0.51503006])

In [82]:
qdafit.means_

array([[ 0.06719008,  0.0221157 ],
       [-0.0297607 , -0.04227237]])

In [84]:
qdapred = qdafit.predict(X_test)

In [85]:
print(confusion_matrix(y_test, qdapred))

[[ 26  92]
 [ 23 111]]


In [87]:
print(classification_report(y_test, qdapred))

              precision    recall  f1-score   support

        Down       0.53      0.22      0.31       118
          Up       0.55      0.83      0.66       134

   micro avg       0.54      0.54      0.54       252
   macro avg       0.54      0.52      0.49       252
weighted avg       0.54      0.54      0.50       252



**In this case, the prediction actually reduces. Although one needs to perform further analysis, this suggests that the QDA model actually introduces greater variance into the model which is not compensated by the reduction in bias, thereby 
leading to a poorer fit (the reverse happens in the book, but that is because the method of selection of training and test data in the book and in this notebook are different.**